In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
dataset = pd.read_csv('Datamining.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [6]:
print(x)

[['Semarang' 38.0 82000.0]
 ['Surabaya' 41.0 90000.0]
 ['Jogja' 35.0 70000.0]
 ['Surabaya' 43.0 89000.0]
 ['Jogja' 44.0 nan]
 ['Semarang' 31.0 94000.0]
 ['Jogja' nan 59000.0]
 ['Surabaya' 35.0 87000.0]
 ['Semarang' 37.0 80000.0]
 ['Surabaya' 50.0 78000.0]]


In [7]:
print(y)

['No' 'Yes' 'Yes' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [9]:
print(x)

[['Semarang' 38.0 82000.0]
 ['Surabaya' 41.0 90000.0]
 ['Jogja' 35.0 70000.0]
 ['Surabaya' 43.0 89000.0]
 ['Jogja' 44.0 81000.0]
 ['Semarang' 31.0 94000.0]
 ['Jogja' 39.333333333333336 59000.0]
 ['Surabaya' 35.0 87000.0]
 ['Semarang' 37.0 80000.0]
 ['Surabaya' 50.0 78000.0]]


In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [15]:
print(x)

[[0.0 1.0 0.0 38.0 82000.0]
 [0.0 0.0 1.0 41.0 90000.0]
 [1.0 0.0 0.0 35.0 70000.0]
 [0.0 0.0 1.0 43.0 89000.0]
 [1.0 0.0 0.0 44.0 81000.0]
 [0.0 1.0 0.0 31.0 94000.0]
 [1.0 0.0 0.0 39.333333333333336 59000.0]
 [0.0 0.0 1.0 35.0 87000.0]
 [0.0 1.0 0.0 37.0 80000.0]
 [0.0 0.0 1.0 50.0 78000.0]]


In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
print(y)

[0 1 1 0 0 1 0 1 0 1]


In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [19]:
print(x_train)

[[1.0 0.0 0.0 39.333333333333336 59000.0]
 [1.0 0.0 0.0 44.0 81000.0]
 [0.0 1.0 0.0 38.0 82000.0]
 [0.0 0.0 1.0 43.0 89000.0]
 [0.0 0.0 1.0 41.0 90000.0]
 [0.0 0.0 1.0 35.0 87000.0]
 [0.0 1.0 0.0 37.0 80000.0]
 [0.0 1.0 0.0 31.0 94000.0]]


In [20]:
print(x_test)

[[1.0 0.0 0.0 35.0 70000.0]
 [0.0 0.0 1.0 50.0 78000.0]]


In [21]:
print(y_train)

[0 0 0 0 1 1 0 1]


In [22]:
print(y_test)

[1 1]


In [23]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [24]:
print(x_train)

[[1.0 0.0 0.0 0.19758463641598462 -2.3581115495452254]
 [1.0 0.0 0.0 1.3622940721312653 -0.17375558786122713]
 [0.0 1.0 0.0 -0.13518948807409634 -0.07446668051195449]
 [0.0 0.0 1.0 1.112713478763705 0.620555670932954]
 [0.0 0.0 1.0 0.6135522920285845 0.7198445782822267]
 [0.0 0.0 1.0 -0.8839312681767771 0.4219778562344087]
 [0.0 1.0 0.0 -0.3847700814416566 -0.2730444952104998]
 [0.0 1.0 0.0 -1.8822536416470181 1.1170002076793173]]


In [25]:
print(x_test)

[[1.0 0.0 0.0 -0.8839312681767771 -1.2659335687032263]
 [0.0 0.0 1.0 2.859777632336627 -0.471622309909045]]
